[package]
name = "dev_shard_manager"
version = "0.1.0"
authors = ["my name <my@email.address>"]

[dependencies]
serenity = { path = "../../", default-features = true }
tokio-core = "~0.1"
futures = "~0.1"
env_logger = "~0.4"

