[package]
name = "01_basic_ping_bot"
version = "0.1.0"
authors = ["my name <my@email.address>"]

[dependencies]
futures-await = "~0.1"
serenity = { path = "../../", default-features = true }
tokio-core = "~0.1"
